### ISSUE TITLE
Robinhood API has changed

### ISSUE THREAD

**Issue by mainstringargs** [ConradWeiser/Unofficial-Robinhood-Api#4]
When I try to log in using this simple code:

```
	public static void main(String[] args) {
		
		RobinhoodApi api = null;
		try {
			api = new RobinhoodApi(<USER>,<PASSWORD>);
		} catch (RobinhoodApiException e) {
			e.printStackTrace();
		}
		
		try {
			System.out.println(api.getAccountData());
		} catch (RobinhoodNotLoggedInException e) {
			e.printStackTrace();
		} catch (RobinhoodApiException e) {
			e.printStackTrace();
		}
	}

```
I get this error:

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at conrad.weiser.robinhood.api.request.RequestManager.makePostRequest(RequestManager.java:110)
	at conrad.weiser.robinhood.api.request.RequestManager.makeApiRequest(RequestManager.java:58)
	at conrad.weiser.robinhood.api.RobinhoodApi.logUserIn(RobinhoodApi.java:129)
	at conrad.weiser.robinhood.api.RobinhoodApi.<init>(RobinhoodApi.java:84)
	at Test.main(Test.java:11)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 8 more
```

Printing out the POST response from Robinhood, gives this:

`<h1>Not Found</h1><p>The requested URL /api-token-auth/ was not found on this server.</p>`

**Comment by ConradWeiser** [comment]
Aha! You beat me to it! I was always afraid that Robinhood would change their API endpoints, since this library has no guarintee from the company that it will continue to work. (Downsides of accessing an unofficial endpoint list)

The commit looks relatively accurate, I'll test things within a day or so and verify that all of the endpoints return correct data. 
Maybe in the process I'll write up JUnit tests.

Much appreciated!
